### ISSUE TITLE
无法运行本项目

### ISSUE THREAD

**Issue by ExerciseBook** [gucong3000/safetree#9]
```
C:\Users\stu\Desktop\st\safetree-master>npm install

> electron@1.6.2 postinstall C:\Users\stu\Desktop\st\safetree-master\node_modules\electron
> node install.js

C:\Users\stu\Desktop\st\safetree-master\node_modules\electron\install.js:46
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
safetree@1.0.0 C:\Users\stu\Desktop\st\safetree-master
`-- dialogs@1.1.18
  +-- brfs@1.4.3
  | +-- quote-stream@1.0.2
  | | +-- buffer-equal@0.0.1
  | | `-- minimist@1.2.0
  | +-- resolve@1.3.2
  | | `-- path-parse@1.0.5
  | +-- static-module@1.3.1
  | | +-- concat-stream@1.4.10
  | | | +-- inherits@2.0.3
  | | | +-- readable-stream@1.1.14
  | | | | `-- isarray@0.0.1
  | | | `-- typedarray@0.0.6
  | | +-- duplexer2@0.0.2
  | | | `-- readable-stream@1.1.14
  | | |   `-- isarray@0.0.1
  | | +-- escodegen@1.3.3
  | | | +-- esprima@1.1.1
  | | | +-- estraverse@1.5.1
  | | | +-- esutils@1.0.0
  | | | `-- source-map@0.1.43
  | | |   `-- amdefine@1.0.1
  | | +-- falafel@1.2.0
  | | | +-- acorn@1.2.2
  | | | +-- foreach@2.0.5
  | | | +-- isarray@0.0.1
  | | | `-- object-keys@1.0.11
  | | +-- has@1.0.1
  | | | `-- function-bind@1.1.0
  | | +-- object-inspect@0.4.0
  | | +-- quote-stream@0.0.0
  | | | `-- minimist@0.0.8
  | | +-- readable-stream@1.0.34
  | | | +-- core-util-is@1.0.2
  | | | +-- isarray@0.0.1
  | | | `-- string_decoder@0.10.31
  | | +-- shallow-copy@0.0.1
  | | +-- static-eval@0.2.4
  | | | `-- escodegen@0.0.28
  | | |   +-- esprima@1.0.4
  | | |   `-- estraverse@1.3.2
  | | `-- through2@0.4.2
  | |   `-- xtend@2.1.2
  | |     `-- object-keys@0.4.0
  | `-- through2@2.0.3
  |   `-- readable-stream@2.2.3
  |     +-- buffer-shims@1.0.0
  |     +-- isarray@1.0.0
  |     +-- process-nextick-args@1.0.7
  |     `-- util-deprecate@1.0.2
  +-- hyperglue@2.0.1
  | `-- domify@0.2.0
  +-- insert-css@0.1.0
  `-- xtend@4.0.1

npm WARN safetree@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.2 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\stu\Desktop\st\safetree-master\npm-debug.log

C:\Users\stu\Desktop\st\safetree-master>
```

[npm-debug.txt](https://github.com/gucong3000/safetree/files/837455/npm-debug.txt)

**Comment by gucong3000** [comment]
electron的安装遇到了网络问题，建议使用国内镜像，windows下运行以下命令安装
```bash
set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/
npm i
```
